### ISSUE TITLE
Get Builds by views

### ISSUE THREAD

**Issue by designgawd** [silas/node-jenkins#10]
Is there a way I can get a list of build jobs by views?

Example: 
http://company.url.com/view/<viewName>/api/json?pretty=true

The use of the above url would give me a list of jobs inside of a view (tabs from UI).

Please let me know if this makes since.

**Comment by silas** [comment]
Just added view support, available in version >= 0.9

```
jenkins.view.get({ name: 'Test View', depth: 1 }, function(err, view) {
  if (err) throw err;

  console.log('Name:', view.name);

  view.jobs.forEach(function(job) {
    console.log('Job:', job.name, 'Status:', job.color);
  });
});
```
