### ISSUE TITLE
Error when fileupload

### ISSUE THREAD

**Issue by ppxnouse** [silas/node-jenkins#117]
There seems to be a small error in the latest jobs.js
https://github.com/silas/node-jenkins/blob/034f18bca391907eed9ddaa6e8bbf8d1f9c179a6/lib/job.js#L54

Should be 
`form.append(name, value);`
 I assume.

**Comment by silas** [comment]
Fixed released in [jenkins@1.0.2](https://www.npmjs.com/package/jenkins/v/1.0.2)
