### ISSUE TITLE
Disable Name URL Encoding

### ISSUE THREAD

**Issue by destroyerofbuilds** [silas/node-jenkins#12]
I'm attempting to call `jenkinsClient.job.config(...)` with something like the following, {folder name} + `/job/` + {job name}, to fetch the configuration of a job (which happens to be in a folder. However, `papi` encodes the name, {folder name} + `%2Fjob%2F` + {job name}.

I'm under the impression that I should be able to encapsulate the job name using `new Buffer(...)`, and append a `encode` property, as a means to disable the encoding. However, `node-jenkins` expects the value passed in to `job.config(...)` to be a string.

Is there a way to pass the name of a folder-embedded job without the value being url encoded?

**Comment by silas** [comment]
I'll take another look (#6) at adding support for the folder plugin, but it's definitely not supported right now.

Just disabling param escaping won't work (ex: to create a job you'd need to parse the name and put the prefix in the path and the suffix in the query parameter / body).

It would also break existing jobs that have spaces and other such characters in the name.

**Comment by silas** [comment]
Should be supported in version `0.10.0` (published to npm), re-open if you run into issues.

**Comment by destroyerofbuilds** [comment]
Seems to be working great with Jenkins folders. Thank you!
