### ISSUE TITLE
How to get the view info which belongs to a sub folder

### ISSUE THREAD

**Issue by mtozjh** [silas/node-jenkins#18]
I am using this excellent package to get jenkins job information.

But I failed to get the view info with the following function call. 

jenkins.view.get("main/MyJobs", ...)

Error: jenkins: view.get: main/MyJobs not found

the "main" is a sub folder I created Jenkins. 

I am able to get job info like blow
jenkins.job.config("main/nightly", ....)

**Comment by silas** [comment]
Thanks for reporting, should be fixed in version `>= 0.12.0` (published to npm).
