### ISSUE TITLE
Jenkins internal server error on canceling queue items

### ISSUE THREAD

**Issue by george-peng-git** [silas/node-jenkins#23]
When one calls jenkins.queue.cancel(<valid queue id>, callback), the callback receives an internal server error (please see attachment for the error), and the queue item is still not removed.
[jenkins_cancel_queue_error.txt](https://github.com/silas/node-jenkins/files/137843/jenkins_cancel_queue_error.txt)

Inspecting lib/queue.js, I find in the method Queue.prototype.cancel has the following statement:
`req.path = '/queue/items/{number}/cancelQueue';`
When the line is changed to:
`req.path = '/queue/item/{number}/cancelQueue';`
calling this method then returns the error "queue.cancel: found" but the queue item is successfully removed.

**Comment by silas** [comment]
Fixed and released in version `0.15.0`.

Thanks for the bug report and fix!
