### ISSUE TITLE
Move test in a subfolder of test

### ISSUE THREAD

**Issue by DanFaudemer** [silas/node-jenkins#26]
Hi,

Thanks for this awesome library! 
I have an issue in my project which is using Jenkins Library. When I moved test in a subfolder of test:

> test/unit

Some tests are failing.
I create a fork from your code which reproduce the issue: 
https://github.com/DanFaudemer/node-jenkins

And run 
`mocha test/unit `

to reproduce the error 

Any idea?

**Comment by silas** [comment]
The node-jenkins tests load fixture data from test/fixtures, which expects them to live in `./test/fixtures`.

**Comment by DanFaudemer** [comment]
Hi Silas,

Thanks this solve the issue ! I though that fixtures files folder need to be in the same directory...
