### ISSUE TITLE
add support for non-api endpoints

### ISSUE THREAD

**Issue by akaRem** [silas/node-jenkins#27]
Jenkins has a little bit strange api.
For example, there is no way to find hostname via api. But it's available through config:
`https://{url}/computer/{node.displayName}/config.xml`

Could you please extend built-in methods with additional calls for such specific cases as it done for job config?

**Comment by silas** [comment]
Sorry about the slow response, this already exists but wasn't documented in the README. I added it.

Thanks for letting me know!
