### ISSUE TITLE
How can I get the build number of the build after running jenkins.job.build()

### ISSUE THREAD

**Issue by TGNC** [silas/node-jenkins#30]
I couldn't find any explanation in the documentation how should I get the build Id of the created build - so I could get it's information and logs.
(also - way the function jenkins.job.build() isn't returning in the callback the data of the created build??)

Thanx a lot for the help.

**Comment by byronrau** [comment]
Yes, I would like know this information as well, thank you!

**Comment by silas** [comment]
When you request a build jenkins creates a queue item, but doesn't assign the build number right away (see https://issues.jenkins-ci.org/browse/JENKINS-12827 for more information).

You basically need to poll the queue.item route until it gets assigned.

Something like the following should work

``` javascript
var jenkins = require('jenkins')('http://user:pass@localhost:8080');

function waitOnQueue(id) {
  jenkins.queue.item(id, function(err, item) {
    if (err) throw err;
    console.log('queue', item);
    if (item.executable) {
      console.log('number:', item.executable.number);
    } else if (item.cancelled) {
      console.log('cancelled');
    } else {
      setTimeout(function() {
        waitOnQueue(id);
      }, 500);
    }
  });
}

jenkins.job.build('test', function(err, id) {
  if (err) throw err;
  waitOnQueue(id);
});
```

**Comment by byronrau** [comment]
Thank you!

**Comment by TGNC** [comment]
Thanks a lot!!

**Comment by hauk0101** [comment]
cool
