### ISSUE TITLE
Get the build log with websocket with jenkins.build.log()

### ISSUE THREAD

**Issue by TGNC** [silas/node-jenkins#32]
I am building an admin app to run my company test and we want to use jenkins.
I want to have in my admin app some sort of print of the console log - like in jenkins itself.

But from what I see - the function jenkins.build.log() is only getting me the current log of the build.
So I need to do create some pulling warper till the build end - to have the updated log printing.

Is there any websocket option? in this client? or in jenkins itself?
And the pulling option is the best approach ? or should I read the created log in the server of jenkins itself?

Thanks for the help

**Comment by minz1027** [comment]
+1! I have the same issue. Is it possible to have a function to return a readable stream for log? 
I noticed that the jenkins API you call in `jenkins.build.log()` is `/consoleText`. There is another api `logText/progressiveText` which provides some headers that might be helpful for streaming, e.g. `x-more-data`.

**Comment by jupe** [comment]
I'm also interested about this

**Comment by silas** [comment]
Published to npm in version 0.19.0

See https://github.com/silas/node-jenkins#build-log-stream fore more info

**Comment by TGNC** [comment]
Silas Sewell this new feature work great!! thanks
