### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by MarinKacaj** [silas/node-jenkins#33]
Hello,
My build needs to receive some files.  However I was unable to find anything in the docs about file uploads. 
Can you please tell me whether there is any way I can upload files with this library?

**Comment by silas** [comment]
It's doesn't right now, but I'll look into adding it.

**Comment by gaborcsardi** [comment]
This would require multipart POST support in papi I think. I would need this feature as well, so I'll consider adding multipart POST support there (https://github.com/silas/node-papi/issues/13) and then file upload support here.

**Comment by gaborcsardi** [comment]
Happening in #52

**Comment by silas** [comment]
Added in 4cad1dad59ea1796a733d61934ab2ef85809799d

**Comment by gaborcsardi** [comment]
Great, thanks much!
