### ISSUE TITLE
Any Chance to get Timestamp in jenkins.job.get()

### ISSUE THREAD

**Issue by chitopunk** [silas/node-jenkins#34]
I'd like to see timestamp of the lastBuild like shown in here.

http://jenkins.company.com/job/my-job/lastBuild/api/json

Thanks

**Comment by silas** [comment]
You can use `depth` to get more data out of `job.get`.

``` javascript
jenkins.job.get({ name: 'test', depth: 1 }, function(err, job) {
  if (err) throw err;

  console.log(job.lastBuild);
});
```

If that's too much data you can filter it down with [tree](https://www.cloudbees.com/blog/taming-jenkins-json-api-depth-and-tree).

``` javascript
jenkins.job.get({ name: 'test', depth: 1, tree: 'name,lastBuild[*]' }, function(err, job) {
  if (err) throw err;

  console.log(job.name, job.lastBuild.timestamp);
});
```

Most calls support the `depth` and `tree` options.

**Comment by chitopunk** [comment]
Thanks!
