### ISSUE TITLE
Passing JSON Object as a parameter to build a job

### ISSUE THREAD

**Issue by ghost** [silas/node-jenkins#44]
How can I trigger a Jenkins job by passing json object as a parameter from 
``jenkins.job.build(name: 'jobname', parameters: object)``

**Comment by wxm45337** [comment]
yes, I have this problem，changed the plug-in source code, you can solve this problem

**Comment by madbean** [comment]
hello,

Y have this error on build action with params
message: 'jenkins: job.build: jenkins: crumbIssuer.get: not found',
statusCode: 404,

`jenkins.job.build({ name: 'dump-anonymiser', parameters: { name: 'test'} }, function(err) {}`

thx for your help

**Comment by silas** [comment]
I'm not sure if this is something that needs a fix in the `node-jenkins` code or not, but if so feel free to re-open.
