### ISSUE TITLE
Support tree parameter for jenkins.build.get method

### ISSUE THREAD

**Issue by androidfanatic** [silas/node-jenkins#47]
Why?

The `/<jobname>/<build_number>/api/json` endpoint returns a huge JSON object for projects with too many artifacts. This can sometimes result in jenkins API taking 2-5 seconds to emit a response. 

Using tree parameter, one can fetch specific fields from build information.

Example URLs: 

```
https://<jenkins_host>/job/<jobname>/lastSuccessfulBuild/api/json?tree=result
https://<jenkins_host>/job/<jobname>/lastSuccessfulBuild/api/json?tree=result,id,duration
```

**Comment by silas** [comment]
`tree` and `depth` are [common options](https://github.com/silas/node-jenkins#common-options) you can pass to any function. You can see an example of it's usage [here](https://github.com/silas/node-jenkins/issues/22#issuecomment-185517593). If it's not working for you feel free to re-open this issue.
