### ISSUE TITLE
Cannot set a custom build url

### ISSUE THREAD

**Issue by L1qu1d1c3** [silas/node-jenkins#49]
Hi,

If I have a custom URL for my builds, for example, in your code you always set the build name as "example" and this means that the url would be jenkinsurldotcom/jenkins/job/example. But what happens when the url isnt /job/example? Because in my organization we have subfolders per department, for example: jenkinsdotcom/jenkins/job/Folder1/job/subfolder/JOBNAME/1
When I try to set that as a custom value, it gives me error:
Error: jenkins: build.get: /CUSTOM/JOB/PATH/JOB_NAME.DEPLOY 1 not found
    at Jenkins.<anonymous> (e:\node_modules\jenkins\lib\middleware.js:82:17)
    at next (e:\node_modules\papi\lib\client.js:300:10)
    at Jenkins._onResponse (e:\node_modules\jenkins\lib\jenkins.js:138:3)
    at next (e:\node_modules\papi\lib\client.js:300:10)
    at IncomingMessage.<anonymous> (e:\node_modules\papi\lib\client.js:600:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)

**Comment by silas** [comment]
If you have a job with a URL like `/job/Infra/job/backend-jenkins-plugin-info-plugin/` you can reference it in this client using the name `Infra/backend-jenkins-plugin-info-plugin`.

If you have some custom prefix on the URL (say if your infrastructure group is proxying it), you need to add the common prefix (looks like possibly `/jenkins` in the example above) to the `baseUrl` when constructing the client.

```
var jenkins = require('jenkins')({ baseUrl: 'https://example.com/jenkins' });

jenkins.job.get('Infra/backend-jenkins-plugin-info-plugin', function(err, data) {
  if (err) throw err;

  console.log('job', data);
});
```

**Comment by L1qu1d1c3** [comment]
I tried this, still tells me that the job cannot be found. Here's my code(some redaction included):

var jenkins = require('jenkins')({baseUrl : 'http://USER:PASS@example.com/jenkins', crumbUser: true});

jenkins.job.get('REDACTED/job/REDACTED/job/REDACTED/job/TEST_AGENT_STANDALONE.DEPLOY', function(err, data) {
            if (err) throw error;
            console.log('job', data);
          });

This tells me:
Error: jenkins: job.get: REDACTED/job/REDACTED/job/REDACTED/job/TEST_AGENT_STANDALONE.DEPLOY not found

**Comment by silas** [comment]
Don't include the `/job/` separator, just use `/`

**Comment by silas** [comment]
This seems to be working correctly in the latest version.

``` javascript
const jenkins = require('./lib')({ baseUrl: 'http://admin:password@localhost:8080' });
jenkins.on('log', console.log);

jenkins.job.get('c55.automation/c55.dev/c55.dev.deploy', () => null);
```

``` javascript
[ 'debug', 'job', 'get' ] { name: 'c55.automation/c55.dev/c55.dev.deploy' }
[ 'papi', 'request', 'jenkins', 'job.get' ] { auth: 'admin:password',
  hostname: 'localhost',
  port: '8080',
  path:
   '/job/c55.automation/job/c55.dev/job/c55.dev.deploy/api/json',
  method: 'GET',
  headers:
   { referer:
      'http://admin:password@localhost:8080/' } }
[ 'papi', 'response', 'jenkins', 'job.get' ] { method: 'GET',
  path:
   '/job/c55.automation/job/c55.dev/job/c55.dev.deploy/api/json',
  statusCode: 404,
  headers:
   { connection: 'close',
     date: 'Thu, 21 Mar 2019 17:37:19 GMT',
     'x-content-type-options': 'nosniff',
     'cache-control': 'must-revalidate,no-cache,no-store',
     'content-type': 'text/html;charset=iso-8859-1',
     'content-length': '373',
     server: 'Jetty(9.4.z-SNAPSHOT)' },
  remoteAddress: '127.0.0.1',
  remotePort: 8080 }
```

If you're seeing something else feel free to add the `jenkins.on('log', console.log);` and re-open the issue.
