### ISSUE TITLE
How to run tests

### ISSUE THREAD

**Issue by louislatreille** [silas/node-jenkins#60]
Hey,

I'd like to contribute to the library. I've added a new functionality that lists jobs in a subdirectory, and now I want to add a test to validate it's working correctly. 

When I run the tests (with `npm test`) it fails to use my jenkins server. I'm getting some `encode (application/x-www-form-urlencoded) failed: utf8 is not a function'` errors. Is there a way we should setup our jenkins server for tests?

**Comment by louislatreille** [comment]
I fixed the above error, but it still looks like the tests have trouble accessing my server. I'm getting errors in before and after hooks.

**Comment by silas** [comment]
I [added](https://github.com/silas/node-jenkins/commit/8d84ecbaaa4174eef7a019d460310ce3f59afe6d) a docker-compose helper for running the acceptance tests, see:

https://github.com/silas/node-jenkins#test

You'll need Docker and docker-compose installed to use it.
