### ISSUE TITLE
Module not found: Error: Can't resolve 'http'. Unable to serve Angular6 application with Jenkins Module

### ISSUE THREAD

**Issue by ranju4u6** [silas/node-jenkins#61]
I am novice in Angular 6 (more appropriately Angular > 1). I am basically trying to pull some data from Jenkins and present in on an Angular backed UI application.

At first, I followed the below tutorial to start with. https://programmingwithmosh.com/angular/angular-4-tutorial/

I ensured that I am able to access the "http://localhost:4200" after performing "ng serve".

To access Jenkins, I used Jenkins module from NPM. https://www.npmjs.com/package/jenkins

Installed the same using npm install jenkins

Then modified the app.component.ts with the following code to pull information from Jenkins.

```
import { Component, OnInit } from '@angular/core';

declare var require: any;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit{
  title = 'Study1Jenkins';

  ngOnInit() {

    var jenkins = require('jenkins')({ baseUrl: 'https://UN:PW@myjenkins.com', crumbIssuer: true });

    jenkins.info(function(err, data) {
      if (err) throw err;

      console.log('info', data);
    });

  }

}
```
Then I tried to do an ng serve which resulted in the following error.

> 
ERROR in ./node_modules/papi/lib/client.js Module not found: Error: Can't resolve 'http' in '\Study1Jenkins\node_modules\papi\lib' ERROR in ./node_modules/papi/lib/client.js Module not found: Error: Can't resolve 'https' in '\Study1Jenkins\node_modules\papi\lib' i ｢wdm｣: Failed to compile.

**Comment by silas** [comment]
This module is built for server side Node.js only. You'll need to make the HTTP calls directly using whatever angular provides or find an alternative library that supports client side setups.
