### ISSUE TITLE
Adding the support of a cli

### ISSUE THREAD

**Issue by dinukadesilva** [silas/node-jenkins#64]
I would really like this since jenkins doesn't have a good npm cli anywhere yet. This could be a good start if we do since this project has the most core for that.

I would like to come up with a plan and contribute if no one is already working already.

**Comment by silas** [comment]
I'm not really interested in maintaining it in this repository, but if it's something your interested I'd say go for it. If you get something published I'm happy to link to it.

**Comment by dinukadesilva** [comment]
Ohh sure... I will do
