### ISSUE TITLE
Proposal, add support for general api endpoints

### ISSUE THREAD

**Issue by rburdet** [silas/node-jenkins#74]
This is related with #27. 

I would like to have a method where you could use your session object to make requests to non standard api like: `{url}/job/{job}/buildHistory/ajax?search={search}` or even standard method for extensibility like `{url}/job/{job}/api`. 

Suppose you want to handle the full json tree yourself: 
```
jenkins.url('/job/{job}/json?depth=1')
```

Or in my particular scenario i would like to do: 

```
jenkins.url('/job/{job}/buildHistory/ajax?search={search}')
```

I could submit the PR if you are interested

**Comment by silas** [comment]
I think you'd probably just end up rebuilding the `_get`, `_post`, etc... methods. Is there a reason you can't use those directly?

Those are part of the [papi API](https://github.com/silas/node-papi/tree/0.29.1#client_requestrequest-callback-callback) and should be relatively stable.

**Comment by silas** [comment]
If the above doesn't work feel free to re-open.
