### ISSUE TITLE
Job list does not support folders

### ISSUE THREAD

**Issue by krische** [silas/node-jenkins#75]
It looks like the `job.list` function does not support folders like the other job functions. The API endpoint used to list the jobs only lists the jobs at that level, so you need to hit a different path to list jobs inside a folder.

For example, `/api/json` will only list the top level jobs and `/job/folder/api/json` will list jobs in the folder.

**Comment by silas** [comment]
Merged #76 in 9864a25faebbd924e61117877c57257958f240dc and published to npm in `jenkins@0.26.0`.
