### ISSUE TITLE
Issue after jenkins csrf updated in v2.189

### ISSUE THREAD

**Issue by Cherviakov** [silas/node-jenkins#81]
Hello, after updating jenkins to v2.189 our server start to get 403 No valid crumb was included in the request error when doing requests via this package. This seems to be due to https://jenkins.io/security/advisory/2019-08-28/, namely CSRF protection tokens for anonymous users did not expire in some circumstances. When I tried to write separate scrpt, which should reproduce problem, it suddenly worked, so I guess jenkins lib caching some request params and we need to reset it, could you please help?

To this date I managed to check that crumb is actually get issued and that it is included in request to jenkins.

**Comment by silas** [comment]
Thanks for reporting the issue. Should be fixed in `jenkins@0.27.0`.
