### ISSUE TITLE
Date on build info

### ISSUE THREAD

**Issue by Joni1992** [silas/node-jenkins#9]
When getting the build info while using this function: 
```javascript
jenkins.build.get(options, callback)
```

Is it possible to get the date on every build, lets say last successful build, last build and so on?

Cheers.

**Comment by silas** [comment]
You can call

```
jenkins.job.get({ name: "myjob", depth: 1 }, callback)
```

Or

```
jenkins.job.list({ depth: 2 }, callback)
```
