### ISSUE TITLE
Creating credential domains and credentials

### ISSUE THREAD

**Issue by bdhoine** [silas/node-jenkins#94]
I would like to contribute to have the possibility to create credentials domains with a specific scope and to create credentials (like username-password). Would that fit in this plugin? I want to make sure that it will be considered as a feature before starting development.

**Comment by silas** [comment]
It's fine as long as there is a dedicated api for it. Do you have any examples of other clients implementing it?

**Comment by bdhoine** [comment]
I did not find any good clients or examples but the docs are very good and also describe a REST API. The examples that you find online usually are nit future proof because they use the forms and not the REST API's. I will base my work on https://github.com/jenkinsci/credentials-plugin/blob/master/docs/user.adoc#managing-an-existing-credentials-instance

**Comment by markmssd** [comment]
Just something to keep in mind is that the credentials REST API changed from the plugins' v1 to v2.

If can help if needed!

**Comment by bdhoine** [comment]
Ok good to know, I based myself on the GitHub docs (so probably only 2.x support) thanks @markmssd! I'm currently wrapping up on the API calls, most of that is finished and the next step is add some tests.
